(prelude-require-packages
 '(project-explorer
   blackboard-theme
   org-pomodoro
   org-projectile
   org-gnome
   ein
   elpy
   company-anaconda
   leuven-theme
   tangotango-theme
   emojify
   langtool
   define-word
   py-autopep8
   clang-format
   rtags
   langtool
   auto-complete-clang
   cpputils-cmake
   cmake-mode
   auctex-latexmk
   writegood-mode)
)
