(prelude-require-packages
 '(project-explorer
   solarized-theme
   blackboard-theme
   org-pomodoro
   org-projectile
   org-gnome
   ein
   elpy
   company-anaconda
   tangotango-theme
   base16-theme
   emojify
   langtool
   define-word
   py-autopep8
   clang-format
   rtags
   auto-complete-clang
   cpputils-cmake
   cmake-mode
   writegood-mode)
)
